name: 'Automation'

on:
  push:
    branches:
      - master
  pull_request_target:
    types:
      - synchronize

jobs:
  triage:
    name: 'Merge conflict labeling'
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'jellyfin/jellyfin-web' }}
    steps:
      - uses: eps1lon/actions-label-merge-conflict@b8bf8341285ec9a4567d4318ba474fee998a6919 # tag=v2.0.1
        with:
          dirtyLabel: 'merge conflict'
          repoToken: ${{ secrets.JF_BOT_TOKEN }}
